name: qrcode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  mobile_scanner: ^6.0.7
  openpgp: ^3.10.1
  path: ^1.9.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  sqflite: ^2.4.1
  url_launcher: ^6.1.10
  intl: ^0.20.2
  image_picker: ^0.8.7+5  # Already in your code
  permission_handler: ^10.2.0  # Already in your code
  wave: ^0.2.2  # Already in your code
  device_info_plus: ^9.1.2
  google_mlkit_barcode_scanning: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
  assets:
    - assets/logo.png
    - assets/inprogress.png
    - assets/home.png
